### ISSUE TITLE
Unsafe eval warning from dependency on React-PDF

### ISSUE THREAD

**Issue by skoldborg** [cyntler/react-doc-viewer#169]
I'm getting a warning about unsafe eval whenever I build my project (using Vite). The warning is coming from the dependency in React-Doc-Viewer on [React-PDF](https://www.npmjs.com/package/react-pdf) which in its turn depends on pdf.js.

This is the error:

```
Use of eval in "node_modules/pdfjs-dist/legacy/build/pdf.js" is strongly discouraged as it poses security risks and may cause issues with minification.
```

According to this thread https://github.com/wojtekmaj/react-pdf/issues/862, a simple change on the import from `pdfjs-dist/legacy/build/` to `pdfjs-dist/build/` would solve the problem. 

Would it be possible to release an update with this fix?

**Comment by skoldborg** [comment]
I cloned the repo and found the culprit immediately. This is the problem:

File: `src/renderers/pdf/index.tsx`

```
pdfjs.GlobalWorkerOptions.workerSrc = `https://unpkg.com/pdfjs-dist@${pdfjs.version}/legacy/build/pdf.worker.min.js`;
```

**Comment by cyntler** [comment]
@skoldborg the library should be working right now after the new version released.

**Comment by skoldborg** [comment]
@cyntler I am still getting the unsafe eval warning from pdf.js. Using v1.14.1.

**Comment by skoldborg** [comment]
@cyntler I am still getting the unsafe eval warning. Using v1.14.1.
