### ISSUE TITLE
Error: require() of ES Module in v.1.10.0

### ISSUE THREAD

**Issue by oscarsson444** [cyntler/react-doc-viewer#86]
Hello!
I get the following error in v.1.10.0

Error: require() of ES Module C:\Users\...\node_modules\csv-parse\dist\esm\index.js from C:\Users\...\node_modules\@cyntler\react-doc-viewer\dist\cjs\plugins\csv\index.js not supported.
Instead change the require of C:\Users\...\node_modules\csv-parse\dist\esm\index.js in C:\Users\...\node_modules\@cyntler\react-doc-viewer\dist\cjs\plugins\csv\index.js to a dynamic import() which is available in all CommonJS modules.

And if i downgrade to v.1.8.0 as was suggested by previous post I get the window is not defined bug instead.

Hope this is enough information to solve it!

**Comment by cyntler** [comment]
@oscarsson444 Should be fixed at v.1.10.1. Confirm please! ;)

**Comment by oscarsson444** [comment]
Thank you for being quick! I still get errors but different, so now i get the following errors (3):

AbortError: The operation was aborted. 
useDocumentLoader/</<
node_modules\@cyntler\react-doc-viewer\dist\esm\hooks\useDocumentLoader.js (43:0)

InvalidCharacterError: String contains an invalid character
HTMLRenderer/<
node_modules\@cyntler\react-doc-viewer\dist\esm\plugins\html\index.js (13:0)

InvalidCharacterError: String contains an invalid character
HTMLRenderer/<
node_modules\@cyntler\react-doc-viewer\dist\esm\plugins\html\index.js (13:0)

The thing I'm trying to do is viewing powerpoint presentations with your package. I tried to upload the powerpoint to drive and get it from there and to store it locally but it did not make a difference. Hope this helps!

**Comment by cyntler** [comment]
@oscarsson444 Can I see your React code? I need also informations like your Node.js version/do you use Next.js or Create React App maybe? What is your bundler?

**Comment by oscarsson444** [comment]
Thanks for responding! I ended up switching techonogies, but the problem seems to be that I am using Next.js and that the pdf.worker did not work in a smooth way with next (maybe issues with webpack but im not sure). Anyways im grateful for your help :)
